# Generated by Django 2.2.5 on 2021-04-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizChooseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whichQ', models.CharField(choices=[('Geonra1', 'Geonra1'), ('Geonra2', 'Geonra2')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('With Spaces', 'With Spaces'), ('Without Spaces', 'Without Spaces'), ('Characteres', 'Characteres'), ('Words', 'Words'), ('Sentences', 'Sentences')], max_length=20)),
                ('text', models.TextField(blank=True)),
                ('result', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
